### ISSUE TITLE
Build is VALID but errors

### ISSUE THREAD

**Issue by rammoozz** [HenrikJoreteg/masters#1]
Hello,

Thank you for the course!
I ran npm install (had to npm install prefixer after) and the build seems to be VALID, but the following errors are in the terminal. I believe it might be a version issue.

Your input is appreciated! 

`
ERROR in ./~/css-loader!./~/postcss-loader!./~/octicons/octicons/octicons.css
Module build failed: TypeError: css.walkAtRules is not a function
    at Processor.remove (/ampersand/masters/node_modules/autoprefixer/lib/processor.js:108:11)
    at plugin (/masters/node_modules/autoprefixer/lib/autoprefixer.js:49:28)
    at LazyResult.run (/Repos/ampersand/masters/node_modules/postcss/lib/lazy-result.js:197:24)
    at  /masters/node_modules/postcss/lib/lazy-result.js:110:37
    at LazyResult.asyncTick ( /masters/node_modules/postcss/lib/lazy-result.js:124:15)
    at processing.Promise.then._this2.processed ( /masters/node_modules/postcss/lib/lazy-result.js:150:20)
    at new Promise ( /masters/node_modules/core-js/modules/es6.promise.js:197:7)
    at LazyResult.async ( /masters/node_modules/postcss/lib/lazy-result.js:147:27)
    at LazyResult.then ( /masters/node_modules/postcss/lib/lazy-result.js:72:21)
    at Object.module.exports ( /masters/node_modules/postcss-loader/index.js:42:32)
 @ ./~/octicons/octicons/octicons.css 4:14-101 13:2-17:4 14:20-107

ERROR in ./~/css-loader!./~/postcss-loader!./~/stylus-loader!./src/styles/main.styl
Module build failed: TypeError: css.walkAtRules is not a function
    at Processor.remove ( /masters/node_modules/autoprefixer/lib/processor.js:108:11)
    at plugin ( /masters/node_modules/autoprefixer/lib/autoprefixer.js:49:28)
    at LazyResult.run ( /masters/node_modules/postcss/lib/lazy-result.js:197:24)
    at  /masters/node_modules/postcss/lib/lazy-result.js:110:37
    at LazyResult.asyncTick ( /masters/node_modules/postcss/lib/lazy-result.js:124:15)
    at processing.Promise.then._this2.processed ( /masters/node_modules/postcss/lib/lazy-result.js:150:20)
    at new Promise ( /masters/node_modules/core-js/modules/es6.promise.js:197:7)
    at LazyResult.async ( /masters/node_modules/postcss/lib/lazy-result.js:147:27)
    at LazyResult.then ( /masters/node_modules/postcss/lib/lazy-result.js:72:21)
    at Object.module.exports ( /masters/node_modules/postcss-loader/index.js:42:32)
 @ ./src/styles/main.styl 4:14-168 13:2-17:4 14:20-174
webpack: bundle is now VALID.
`

**Comment by justinchristensen66** [comment]
I get the same problem.                                                                                                                                Also, how come there is not a unfinished and finished version of the project?

**Comment by HenrikJoreteg** [comment]
sorry about this! There was a dependency issue causing this :-/ if you have any more issues please let me know.

**Comment by HenrikJoreteg** [comment]
@justinchristensen66 there's now a branch called "start" that will give you the bare-bones starting point: https://github.com/HenrikJoreteg/masters/tree/start
