### ISSUE TITLE
Stylus dependency issue

### ISSUE THREAD

**Issue by rawrmonstar** [HenrikJoreteg/masters#2]
There is a dependency issue with Stylus where you get the below error following the Front End Masters course in the Foundations of Web Applications > Creating Styles section.

```
ERROR in ./~/css-loader!./~/postcss-loader!./~/stylus-loader!./src/styles/main.styl
Module build failed: TypeError: /Users/tegan/Dev/front-end-masters/masters/src/styles/main.styl:2:21
   1| body
   2|   background: purple
--------------------------^

Path must be a string. Received undefined

    at assertPath (path.js:7:11)
    at extname (path.js:1429:5)
    at new SourceMapper (/Users/tegan/Dev/front-end-masters/masters/node_modules/stylus/lib/visitor/sourcemapper.js:41:7)
    at Renderer.render (/Users/tegan/Dev/front-end-masters/masters/node_modules/stylus/lib/renderer.js:94:9)
    at /Users/tegan/Dev/front-end-masters/masters/node_modules/stylus-loader/index.js:149:12
    at tryCatchReject (/Users/tegan/Dev/front-end-masters/masters/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/Users/tegan/Dev/front-end-masters/masters/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/Users/tegan/Dev/front-end-masters/masters/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/Users/tegan/Dev/front-end-masters/masters/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/Users/tegan/Dev/front-end-masters/masters/node_modules/when/lib/Scheduler.js:62:19)
 @ ./src/styles/main.styl 4:14-168 13:2-17:4 14:20-174
```

It works if you update the `"stylus-loader"` dependency in the package.json to `"^2.0.0"` but since I haven't completed the course I don't know if the new version introduces other issues.

**Comment by thiagodebastos** [comment]
I got the same issue. Its so frustrating looking for a reliable source to learn React from. So far the biggest barrier seems to be webpack. Its a monster and I have yet to find a boilerplate or tutorial blog|video that isn't broken. Its super frustrating getting a few hours in only to realise that the build now breaks and you need to resolve it, but resolving it starts to take longer than you've spent on learning React!

EDIT: 2016/08/18
to fix:
- update `"stylus-loader"` to `"^2.0.0"` like @rawrmonstar noted
- install stylus: `npm i -S stylus`

I've submitted PR #3 to fix this issue.
